name: Build & Lint
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    #core
    - name: Install core dependencies
      working-directory: ./packages/core
      run: npm install

    - name: Lint core package
      working-directory: ./packages/core
      run: npm run lint

    - name: Build core package
      working-directory: ./packages/core
      run: npm run build

    #daterange
    - name: Install daterange dependencies
      working-directory: ./packages/daterange
      run: npm install

    - name: Lint daterange package
      working-directory: ./packages/daterange
      run: npm run lint

    - name: Build daterange package
      working-directory: ./packages/daterange
      run: npm run build

    #list-field
    - name: Install list-field dependencies
      working-directory: ./packages/list-field
      run: npm install

    - name: Lint list-field package
      working-directory: ./packages/list-field
      run: npm run lint

    - name: Build list-field package
      working-directory: ./packages/list-field
      run: npm run build

    #rating
    - name: Install rating dependencies
      working-directory: ./packages/rating
      run: npm install

    - name: Lint rating package
      working-directory: ./packages/rating
      run: npm run lint

    - name: Build rating package
      working-directory: ./packages/rating
      run: npm run build

    #ritchtext
    - name: Install ritchtext dependencies
      working-directory: ./packages/ritchtext
      run: npm install

    - name: Lint ritchtext package
      working-directory: ./packages/ritchtext
      run: npm run lint

    - name: Build ritchtext package
      working-directory: ./packages/ritchtext
      run: npm run build

    #tabs
    - name: Install tabs dependencies
      working-directory: ./packages/tabs
      run: npm install

    - name: Lint tabs package
      working-directory: ./packages/tabs
      run: npm run lint

    - name: Build tabs package
      working-directory: ./packages/tabs
      run: npm run build

    #vue
    - name: Install vue dependencies
      working-directory: ./packages/vue
      run: npm install

    - name: Lint vue package
      working-directory: ./packages/vue
      run: npm run lint

    - name: Build vue package
      working-directory: ./packages/vue
      run: npm run build
